site_name: FTC Team 25753 Cyberbots
site_url: https://mydomain.org/mysite
theme:
  name: material
  logo: assets/Cyberbots_logo-removebg-preview-removebg-preview.png
  features:
    - navigation.instant
  palette:
    primary: custom
    accent: cyan
plugins:
  - live-edit
extra_css:
  - stylesheets/extra.css